class SizeManagement:
    def __init__(self): ...
    async def get_size(self): ...
    async def get_sizes(self): ...
    async def create_sizes(self): ...
    async def update_sizes(self): ...
    async def delete_sizes(self): ...
