from .auth_router import router as auth_router
from .user_router import router as user_router
from .branch_router import router as branch_router
from .table_router import router as table_router
from .category_router import router as category_router
from .product_router import router as product_router
from .size_router import router as size_router
from .extra_router import router as extra_router
from .order_router import router as order_router
from .history_router import router as history_router
from .menu_router import router as menu_router
